### 多数据源配置,集成druid连接池 ###
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      sys:
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=sys
        username: postgres
        password: 123456
      basedata:
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=basedata
        username: postgres
        password: 123456
      initial-size: 2
      min-idle: 5
      max-active: 10
      max-wait: 5000
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18000
      web-stat-filter:
        enabled: true
        exclusions: js,gif,jpg,png,css,ico,/druid/*
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: druid2025
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
